services:
  homepage:
    image: nginx:alpine
    container_name: homepage
    volumes:
      - ./dist:/usr/share/nginx/html
    restart: unless-stopped 
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
